name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Setup yarn cache
        id: yarncache
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Build
        env:
          ASSETS_PREFIX: ${{ secrets.ASSETS_PREFIX }}
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
